version: '3.8'

services:
  corporate-bot:
    build: .
    container_name: corporate-ai-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
    volumes:
      - ./config.env:/app/config.env:ro
      - ./credentials.json:/app/credentials.json:ro
      - ./token.pickle:/app/token.pickle
      - ./users.db:/app/users.db
    ports:
      - "8000:8000"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 